/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#6ab149", 
        "secondary": "#2d8bc9", 
        "background-light": "#ffffff",
        "background-alt": "#f8fafc",
        "accent-dark": "#0f172a",
        "secondary-container": "#e1e3de",
        "inverse-on-surface": "#eff1ef",
        "on-secondary-fixed-variant": "#454744",
        "on-error": "#ffffff",
        "inverse-primary": "#7ddc7a",
        "on-background": "#191c1b",
        "on-tertiary-container": "#690034",
        "primary-fixed-dim": "#7ddc7a",
        "surface-container-low": "#f2f4f2",
        "on-secondary-fixed": "#191c1a",
        "on-surface-variant": "#3f4a3c",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-container": "#eceeec",
        "primary-fixed": "#98f994",
        "on-surface": "#191c1b",
        "error-container": "#ffdad6",
        "surface-tint": "#6ab149",
        "on-tertiary-fixed-variant": "#861948",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8faf8",
        "inverse-surface": "#2e3130",
        "on-primary-fixed": "#002204",
        "surface": "#f8faf8",
        "tertiary-fixed-dim": "#ffb1c7",
        "on-tertiary-fixed": "#3e001c",
        "outline-variant": "#becab9",
        "tertiary-fixed": "#ffd9e2",
        "on-primary-fixed-variant": "#005313",
        "on-secondary-container": "#626561",
        "secondary-fixed": "#e1e3de",
        "tertiary": "#a63360",
        "surface-dim": "#d8dad9",
        "tertiary-container": "#f26f9d",
        "on-secondary": "#ffffff",
        "outline": "#6f7a6b",
        "secondary-fixed-dim": "#c5c7c3",
        "on-primary-container": "#003c0b",
        "surface-container-highest": "#e1e3e1",
        "surface-container-high": "#e6e9e7",
        "primary-container": "#51ae53",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-variant": "#e1e3e1",
        "background": "#f8faf8"
      },
      borderRadius: {
        "DEFAULT": "0.375rem",
        "lg": "0.75rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Sora", "sans-serif"],
        "headline": ["Manrope", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        sans: ["Inter", "Arial", "sans-serif"],
      }
    },
  },
  plugins: [],
}